#!/usr/bin/env bash
# A script that installs, configure nginx and redirects

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/jossvega103 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
