#!/usr/bin/env bash
# A script that installs, configure nginx and redirects

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
