#!/usr/bin/env bash
# Debugging nginx not listening on port 80

# Check if nginx is installed
nginx -v

# Update packages
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Makesure nginx is running
sudo service nginx status

# Start nginx
sudo service nginx start

# Set nginx to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
