#!/usr/bin/env bash
# This script manages manage_my_process
# When passing the argument start:
#       1. Starts manage_my_process
#       2. Creates a file containing its PID in /var/run/my_process.pid
#       3. Displays manage_my_process started
# When passing the argument stop:
#       1. Stops manage_my_process
#       2. Deletes the file /var/run/my_process.pid
#       3. Displays manage_my_process stopped
# When passing the argument restart:
#	1. Stops manage_my_process
#	2. Deletes the file /var/run/my_process.pid
#	3. Starts manage_my_process
#	4. Creates a file containing its PID in /var/run/my_process.pid
#	5. Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

PID_FILE="/var/run/my_process.pid"
MANAGE_MY_PROCESS="./manage_my_process"

start() {
	if [ -f "$PID_FILE" ]; then
		echo "manage_my_process is already running"
	else
		$MANAGE_MY_PROCESS &
		echo $! > "$PID_FILE"
		echo "manage_my_process started"
	fi
}

stop() {
	if [ -f "$PID_FILE" ]; then
		kill "$(cat "$PID_FILE")"
		rm -f "$PID_FILE"
		echo "manage_my_process stopped"
	else
		echo "manage_my_process is not running"
	fi
}

restart() {
	stop
	$MANAGE_MY_PROCESS &
	echo $! > "$PID_FILE"
	echo "manage_my_process restarted"

}

usage() {
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		usage
		;;
esac
