#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# - It only displays username, user id and Home directory path for the user.

while IFS=: read -r username _ user_id _ _ _ home_dir _; do
        echo "$username:$user_id:$home_dir"
done < /etc/passwd
