#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

# Initialize a counter variable
count=1

# Use thw hile loop to display the text
while [ $count -le 10 ]; do
	echo "Best School"
	(( count++ ))
done
