#!/usr/bin/env bash
# This script print "Best Schoo" 10 times but the ninth iteration is "Hi"

# Initialize a counter
count=1

while [ "$count" -le 10 ]; do
	if [ "$count" -ne 9 ]; then
		echo "Best School"
	else
		echo "Hi"
	fi
	(( count++ ))
done
