#!/usr/bin/env bash
# This script print "Best Schoo" 10 times but the ninth iteration is "Hi"

for ((i = 0; i <= 10; i++)); do
	if [ "$i" -ne 9 ]; then
		echo "Best School"
	else
		echo "Hi"
	fi
done
