#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hours=1

while [ "$hours" -le 12 ]; do
	echo "Hours: $hours"
	minutes=1
	while [ "$minutes" -le 59 ]; do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
