#!/usr/bin/env bash
# This script displays the content of the current directory

# Loop through all non-hidden files in the current directory
for file in *; do
	# Check if the file is not hidden and is a regular file
	if [[ ! "$file" =~ ^\. && -f "$file" ]]; then
		echo "${file#*-}"
	fi
done
